// Generated by psc-bundle 0.7.4.1
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["Prelude"];
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };                                                                     
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });                 
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (__dict_Applicative_2) {
      return pure(__dict_Applicative_2);
  };
  var map = function (dict) {
      return dict.map;
  };
  var $less$dollar$greater = function (__dict_Functor_5) {
      return map(__dict_Functor_5);
  };
  var compose = function (dict) {
      return dict.compose;
  };
  var functorFn = new Functor(compose(semigroupoidFn));
  var bind = function (dict) {
      return dict.bind;
  };
  var $greater$greater$eq = function (__dict_Bind_24) {
      return bind(__dict_Bind_24);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (__dict_Apply_25) {
      return apply(__dict_Apply_25);
  };
  var liftA1 = function (__dict_Applicative_26) {
      return function (f) {
          return function (a) {
              return $less$times$greater(__dict_Applicative_26["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_26)(f))(a);
          };
      };
  };
  var ap = function (__dict_Monad_30) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(f)(function (_12) {
                  return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(a)(function (_11) {
                      return $$return(__dict_Monad_30["__superclass_Prelude.Applicative_0"]())(_12(_11));
                  });
              });
          };
      };
  };
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["Semigroupoid"] = Semigroupoid;
  exports["ap"] = ap;
  exports["return"] = $$return;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["apply"] = apply;
  exports["<$>"] = $less$dollar$greater;
  exports["map"] = map;
  exports["compose"] = compose;
  exports["semigroupoidFn"] = semigroupoidFn;
  exports["functorFn"] = functorFn;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module DOM.HTML

  exports.window = function () {
    return window;
  };
 
})(PS["DOM.HTML"] = PS["DOM.HTML"] || {});
(function(exports) {
  "use strict";

  // module Unsafe.Coerce

  exports.unsafeCoerce = function(x) { return x; }
 
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["Unsafe.Coerce"];
  exports["unsafeCoerce"] = $foreign.unsafeCoerce;;
 
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["DOM.HTML.Types"];
  var Prelude = PS["Prelude"];
  var Data_Either = PS["Data.Either"];
  var Data_Foreign = PS["Data.Foreign"];
  var Data_Foreign_Class = PS["Data.Foreign.Class"];
  var DOM_Event_Types = PS["DOM.Event.Types"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];                  
  var htmlElementToElement = Unsafe_Coerce.unsafeCoerce;
  exports["htmlElementToElement"] = htmlElementToElement;;
 
})(PS["DOM.HTML.Types"] = PS["DOM.HTML.Types"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["DOM.HTML"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["window"] = $foreign.window;;
 
})(PS["DOM.HTML"] = PS["DOM.HTML"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module DOM.HTML.Document

  exports.body = function (doc) {
    return function () {
      return doc.body;
    };
  };
 
})(PS["DOM.HTML.Document"] = PS["DOM.HTML.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";          

  exports.nullable = function(a, r, f) {
      return a == null ? r : f(a);
  }; 
 
})(PS["Data.Nullable"] = PS["Data.Nullable"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;;
 
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["Data.Nullable"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Function = PS["Data.Function"];                              
  var toMaybe = function (n) {
      return $foreign.nullable(n, Data_Maybe.Nothing.value, Data_Maybe.Just.create);
  };
  exports["toMaybe"] = toMaybe;;
 
})(PS["Data.Nullable"] = PS["Data.Nullable"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["DOM.HTML.Document"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Nullable = PS["Data.Nullable"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["body"] = $foreign.body;;
 
})(PS["DOM.HTML.Document"] = PS["DOM.HTML.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module DOM.HTML.Window

  exports.document = function (window) {
    return function () {
      return window.document;
    };
  };
 
})(PS["DOM.HTML.Window"] = PS["DOM.HTML.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["DOM.HTML.Window"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["document"] = $foreign.document;;
 
})(PS["DOM.HTML.Window"] = PS["DOM.HTML.Window"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Maybe.Unsafe

  exports.unsafeThrow = function (msg) {
    throw new Error(msg);
  };
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["Data.Maybe.Unsafe"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];     
  var fromJust = function (_217) {
      if (_217 instanceof Data_Maybe.Just) {
          return _217.value0;
      };
      if (_217 instanceof Data_Maybe.Nothing) {
          return $foreign.unsafeThrow("Data.Maybe.Unsafe.fromJust called on Nothing");
      };
      throw new Error("Failed pattern match at Data.Maybe.Unsafe line 10, column 1 - line 11, column 1: " + [ _217.constructor.name ]);
  };
  exports["fromJust"] = fromJust;;
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.createElement = function(clazz) {
    return function(props) {
      return function(children){
        return React.createElement.apply(React, [clazz, props].concat(children));
      };
    };
  };

  exports.render = function(element) {
    return function(container) {
      return function() {
        return React.render(element, container);
      }
    };
  };                                            
 
})(PS["React"] = PS["React"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["React"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  exports["render"] = $foreign.render;
  exports["createElement"] = $foreign.createElement;;
 
})(PS["React"] = PS["React"] || {});
(function(exports) {
  "use strict";

  // module React.Bootstrap.Button

  //var ReactBootstrap = require('react-bootstrap');

  exports.buttonClass = ReactBootstrap.Button;
  exports.buttonToolbarClass = ReactBootstrap.ButtonToolbar;
  exports.buttonGroupClass = ReactBootstrap.ButtonGroup;
  exports.dropdownButtonClass = ReactBootstrap.DropdownButton;
  exports.menuItemClass = ReactBootstrap.MenuItem;
 
})(PS["React.Bootstrap.Button"] = PS["React.Bootstrap.Button"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["React.Bootstrap.Button"];
  var React = PS["React"];                                        
  var menuItem = React.createElement($foreign.menuItemClass);                 
  var dropdownButton = React.createElement($foreign.dropdownButtonClass);
  var button_ = React.createElement($foreign.buttonClass)({});
  var buttonToolbar_ = React.createElement($foreign.buttonToolbarClass)({});
  var buttonGroup_ = React.createElement($foreign.buttonGroupClass)({});
  var buttonGroup = React.createElement($foreign.buttonGroupClass);
  var button = React.createElement($foreign.buttonClass);
  exports["menuItem"] = menuItem;
  exports["dropdownButton"] = dropdownButton;
  exports["buttonGroup_"] = buttonGroup_;
  exports["buttonGroup"] = buttonGroup;
  exports["buttonToolbar_"] = buttonToolbar_;
  exports["button_"] = button_;
  exports["button"] = button;;
 
})(PS["React.Bootstrap.Button"] = PS["React.Bootstrap.Button"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module React.DOM

  function mkProps(props) {
      var result = {};

      for (var i = 0, len = props.length; i < len; i++) {
          var prop = props[i];

          for (var key in prop) {
              if (prop.hasOwnProperty(key)) {
                  result[key] = prop[key];
              }
          }
      }

      return result;
  };

  exports.mkDOM = function(tagName) {
      return function(props) {
          return function(children) {
              return React.createElement(tagName, props.length > 0 ? mkProps(props) : null, children);
          }
      }
  };

  exports.text = function(text) {
      return text;
  };
 
})(PS["React.DOM"] = PS["React.DOM"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module React.DOM.Props

  exports.unsafeMkProps = function(key) {
      return function(value) {
          var result = {};
          result[key] = value;
          return result;
      };
  };

  exports.unsafeUnfoldProps = function(key) {
      return function(value) {
          var result = {};

          for (var subprop in value) {
              if (value.hasOwnProperty(subprop)) {
                  result[key + '-' + subprop] = value[subprop];
              }
          }

          return result;
      };
  };
 
})(PS["React.DOM.Props"] = PS["React.DOM.Props"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["React.DOM.Props"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];                          
  var style = $foreign.unsafeUnfoldProps("style");
  var className = $foreign.unsafeMkProps("className");
  exports["className"] = className;
  exports["style"] = style;;
 
})(PS["React.DOM.Props"] = PS["React.DOM.Props"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var $foreign = PS["React.DOM"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];
  var React_DOM_Props = PS["React.DOM.Props"];
  var div = $foreign.mkDOM("div");
  var div$prime = div([  ]);
  exports["div'"] = div$prime;
  exports["div"] = div;
  exports["text"] = $foreign.text;;
 
})(PS["React.DOM"] = PS["React.DOM"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.1
  "use strict";
  var React_Bootstrap_Button = PS["React.Bootstrap.Button"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var Data_Nullable = PS["Data.Nullable"];
  var DOM = PS["DOM"];
  var DOM_HTML = PS["DOM.HTML"];
  var DOM_HTML_Document = PS["DOM.HTML.Document"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  var DOM_HTML_Window = PS["DOM.HTML.Window"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var React = PS["React"];
  var React_DOM = PS["React.DOM"];
  var React_Bootstrap = PS["React.Bootstrap"];
  var React_DOM_Props = PS["React.DOM.Props"];     
  var main = (function () {
      var leftMiddleRight = function (props) {
          return React_Bootstrap_Button.buttonGroup(props)([ React_Bootstrap_Button.button_([ React_DOM.text("Left") ]), React_Bootstrap_Button.button_([ React_DOM.text("Middle") ]), React_Bootstrap_Button.button_([ React_DOM.text("Right") ]) ]);
      };
      var buttonPair = function (props1) {
          return function (props2) {
              return function (txt) {
                  return [ React_Bootstrap_Button.button(props1)([ React_DOM.text(txt) ]), React_Bootstrap_Button.button(props2)([ React_DOM.text(txt) ]) ];
              };
          };
      };
      var sizeButtonToolbar = function (_3) {
          return function (txt) {
              if (_3 instanceof Data_Maybe.Just) {
                  return React_Bootstrap_Button.buttonToolbar_(buttonPair({
                      bsStyle: "primary", 
                      bsSize: _3.value0
                  })({
                      bsSize: _3.value0
                  })(txt));
              };
              if (_3 instanceof Data_Maybe.Nothing) {
                  return React_Bootstrap_Button.buttonToolbar_(buttonPair({
                      bsStyle: "primary"
                  })({})(txt));
              };
              throw new Error("Failed pattern match at Test.Main line 26, column 1 - line 124, column 35: " + [ _3.constructor.name, txt.constructor.name ]);
          };
      };
      var ui = React_DOM["div'"]([ React_Bootstrap_Button.buttonToolbar_([ React_Bootstrap_Button.button_([ React_DOM.text("Default") ]), React_Bootstrap_Button.button({
          bsStyle: "primary"
      })([ React_DOM.text("Primary") ]), React_Bootstrap_Button.button({
          bsStyle: "success"
      })([ React_DOM.text("Success") ]), React_Bootstrap_Button.button({
          bsStyle: "info"
      })([ React_DOM.text("Info") ]), React_Bootstrap_Button.button({
          bsStyle: "warning"
      })([ React_DOM.text("Warning") ]), React_Bootstrap_Button.button({
          bsStyle: "danger"
      })([ React_DOM.text("Danger") ]), React_Bootstrap_Button.button({
          bsStyle: "link", 
          href: "http://react-bootstrap.github.io/"
      })([ React_DOM.text("Link") ]) ]), React_DOM["div'"]([ sizeButtonToolbar(new Data_Maybe.Just("large"))("Large button"), sizeButtonToolbar(Data_Maybe.Nothing.value)("Default button"), sizeButtonToolbar(new Data_Maybe.Just("small"))("Small button"), sizeButtonToolbar(new Data_Maybe.Just("xsmall"))("Extra small button") ]), React_DOM.div([ React_DOM_Props.className("well"), React_DOM_Props.style({
          maxWidth: 400, 
          margin: "0 auto 10px"
      }) ])([ React_Bootstrap_Button.button({
          bStyle: "primary", 
          bsSize: "large", 
          block: true
      })([ React_DOM.text("Block level button") ]), React_Bootstrap_Button.button({
          bsSize: "large", 
          block: true
      })([ React_DOM.text("Block level button") ]) ]), React_DOM["div'"]([ React_Bootstrap_Button.buttonToolbar_([ React_Bootstrap_Button.button({
          bStyle: "primary", 
          bsSize: "large", 
          active: true
      })([ React_DOM.text("Primary button") ]), React_Bootstrap_Button.button({
          bsSize: "large", 
          active: true
      })([ React_DOM.text("Primary button") ]) ]) ]), React_DOM["div'"]([ React_Bootstrap_Button.buttonToolbar_(buttonPair({
          bStyle: "primary", 
          bsSize: "large", 
          disabled: true
      })({
          bsSize: "large", 
          disabled: true
      })("Primary button")) ]), React_DOM["div'"]([ React_Bootstrap_Button.button({
          href: "#"
      })([ React_DOM.text("Link") ]), React_Bootstrap_Button.button_([ React_DOM.text("Button") ]) ]), React_DOM["div'"]([ leftMiddleRight({}) ]), React_DOM["div'"]([ React_Bootstrap_Button.buttonToolbar_([ React_Bootstrap_Button.buttonGroup_([ React_Bootstrap_Button.button_([ React_DOM.text("1") ]), React_Bootstrap_Button.button_([ React_DOM.text("2") ]), React_Bootstrap_Button.button_([ React_DOM.text("3") ]), React_Bootstrap_Button.button_([ React_DOM.text("4") ]) ]), React_Bootstrap_Button.buttonGroup_([ React_Bootstrap_Button.button_([ React_DOM.text("5") ]), React_Bootstrap_Button.button_([ React_DOM.text("6") ]), React_Bootstrap_Button.button_([ React_DOM.text("7") ]) ]), React_Bootstrap_Button.buttonGroup_([ React_Bootstrap_Button.button_([ React_DOM.text("8") ]) ]) ]) ]), React_DOM["div'"]([ React_Bootstrap_Button.buttonToolbar_([ leftMiddleRight({
          bsSize: "large"
      }) ]), React_Bootstrap_Button.buttonToolbar_([ leftMiddleRight({}) ]), React_Bootstrap_Button.buttonToolbar_([ leftMiddleRight({
          bsSize: "small"
      }) ]), React_Bootstrap_Button.buttonToolbar_([ leftMiddleRight({
          bsSize: "xsmall"
      }) ]) ]), React_DOM["div'"]([ React_Bootstrap_Button.buttonGroup_([ React_Bootstrap_Button.button_([ React_DOM.text("1") ]), React_Bootstrap_Button.button_([ React_DOM.text("2") ]), React_Bootstrap_Button.button_([ React_DOM.text("3") ]), React_Bootstrap_Button.dropdownButton({
          title: React_DOM.text("Dropdown"), 
          id: "bg-nested-dropdown"
      })([ React_Bootstrap_Button.menuItem({
          eventKey: "1"
      })([ React_DOM.text("Dropdown link") ]), React_Bootstrap_Button.menuItem({
          eventKey: "1"
      })([ React_DOM.text("Dropdown link") ]) ]) ]) ]) ]);
      var body$prime = function __do() {
          var _2 = DOM_HTML.window();
          var _1 = DOM_HTML_Window.document(_2)();
          var _0 = Prelude["<$>"](Control_Monad_Eff.functorEff)(Prelude["<$>"](Prelude.functorFn)(Data_Maybe_Unsafe.fromJust)(Data_Nullable.toMaybe))(DOM_HTML_Document.body(_1))();
          return Prelude["return"](Control_Monad_Eff.applicativeEff)(DOM_HTML_Types.htmlElementToElement(_0))();
      };
      return Prelude[">>="](Control_Monad_Eff.bindEff)(body$prime)(React.render(ui));
  })();
  exports["main"] = main;;
 
})(PS["Test.Main"] = PS["Test.Main"] || {});

PS["Test.Main"].main();